[providers]
node = true

[phases.setup]
nixPkgs = ['nodejs_18', 'npm']
nixOverlays = []

[phases.build]
cmds = ['npm ci', 'npm run build']

[phases.start]
cmd = 'npm run preview'

[variables]
NODE_ENV = 'production'
