[providers]
node = true

[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[phases.start]
cmd = 'npm run preview'

[variables]
NODE_ENV = 'production'
