[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"
watchPatterns = ["src/**", "public/**", "package.json", "vite.config.ts"]

[deploy]
startCommand = "npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
NIXPACKS_NODE_VERSION = "18"

[experimental]
incrementalBuilds = true