AWSTemplateFormatVersion: '2010-09-09'
Description: 'Supabase Studio oficial en AWS Amplify Hosting'

Resources:
  # Aplicación Amplify para Studio
  SupabaseStudioApp:
    Type: AWS::Amplify::App
    Properties:
      Name: supabase-studio-official
      Description: Supabase Studio oficial self-hosted
      Repository: https://github.com/supabase/supabase
      Platform: WEB
      BuildSpec: |
        version: 1
        applications:
          - appRoot: apps/studio
            frontend:
              phases:
                preBuild:
                  commands:
                    - cd apps/studio
                    - npm ci
                build:
                  commands:
                    - npm run build
                    - npm run export
              artifacts:
                baseDirectory: apps/studio/out
                files:
                  - '**/*'
              cache:
                paths:
                  - apps/studio/node_modules/**/*
      EnvironmentVariables:
        - Name: NEXT_PUBLIC_SUPABASE_URL
          Value: https://d2bxqn3xh4v4kj.cloudfront.net
        - Name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOuoJeHxjNa-NEHVqH3K3ta6lVJpE0-0ZAi0
        - Name: SUPABASE_SERVICE_KEY
          Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
        - Name: DEFAULT_ORGANIZATION_NAME
          Value: AWS Organization
        - Name: DEFAULT_PROJECT_NAME
          Value: AWS Supabase
      Tags:
        - Key: Project
          Value: supabase-studio
        - Key: Environment
          Value: production

  # Branch master
  SupabaseStudioBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt SupabaseStudioApp.AppId
      BranchName: master
      EnableAutoBuild: true
      Framework: Next.js - SSR
      Stage: PRODUCTION
      Tags:
        - Key: Environment
          Value: production

Outputs:
  StudioURL:
    Description: URL de Supabase Studio oficial
    Value: !Sub "https://master.${SupabaseStudioApp.DefaultDomain}"
    Export:
      Name: !Sub "${AWS::StackName}-studio-url"
  
  AppId:
    Description: Amplify App ID
    Value: !GetAtt SupabaseStudioApp.AppId
    Export:
      Name: !Sub "${AWS::StackName}-app-id"
