/**
 * ============================================
 * MODAL DE TRANSFERENCIA DE LLAMADA
 * ============================================
 * 
 * Componente reutilizable para solicitar transferencia de llamada.
 * Incluye razones predefinidas y mensaje personalizado generado por IA.
 */

import React, { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, ArrowRightLeft, Wand2, Loader2, CheckCircle, RotateCcw } from 'lucide-react';
import { analysisSupabase } from '../../config/analysisSupabase';

// Razones predefinidas de transferencia
const TRANSFER_REASONS = [
  {
    short: 'Mejor precio exclusivo',
    full: 'Mi supervisor puede ofrecerle un mejor precio exclusivo que tengo autorización limitada'
  },
  {
    short: 'Caso especial',
    full: 'Mi supervisor maneja casos especiales como el suyo y quiere atenderle personalmente'
  },
  {
    short: 'Beneficios adicionales',
    full: 'Tengo un supervisor especializado en su destino que puede darle beneficios adicionales'
  },
  {
    short: 'Disponibilidad limitada',
    full: 'Mi supervisor tiene disponibilidad muy limitada solo para hoy y quiere hablar con usted'
  },
  {
    short: 'Oferta especial',
    full: 'Como mostró tanto interés, mi supervisor quiere ofrecerle algo especial que yo no puedo autorizar'
  },
];

export interface TransferCallData {
  call_id: string;
  control_url?: string;
  prospecto_id?: string;
  nombre_completo?: string;
  nombre_whatsapp?: string;
  whatsapp?: string;
  checkpoint_venta_actual?: string;
  destino_preferido?: string;
  principales_objeciones?: string;
  fecha_llamada?: string;
  duracion_segundos?: number;
  datos_llamada?: any;
  datos_proceso?: any;
}

interface TransferModalProps {
  isOpen: boolean;
  onClose: () => void;
  call: TransferCallData | null;
  onTransferSuccess?: () => void;
  zIndex?: number;
}

export const TransferModal: React.FC<TransferModalProps> = ({
  isOpen,
  onClose,
  call,
  onTransferSuccess,
  zIndex = 200
}) => {
  // Estados
  const [selectedPresetReason, setSelectedPresetReason] = useState('');
  const [customTransferMessage, setCustomTransferMessage] = useState('');
  const [autoGeneratedMessage, setAutoGeneratedMessage] = useState<string | null>(null);
  const [loadingCustomMessage, setLoadingCustomMessage] = useState(false);
  const [customMessageError, setCustomMessageError] = useState<string | null>(null);
  const [transferLoading, setTransferLoading] = useState(false);

  // Reset estados cuando se abre el modal
  useEffect(() => {
    if (isOpen && call?.prospecto_id) {
      setSelectedPresetReason('');
      setCustomTransferMessage('');
      setAutoGeneratedMessage(null);
      setCustomMessageError(null);
      // Cargar mensaje personalizado automáticamente
      loadCustomMessage(call.prospecto_id);
    }
  }, [isOpen, call?.prospecto_id]);

  // Función para cargar mensaje personalizado desde webhook
  const loadCustomMessage = async (prospectId: string) => {
    if (!prospectId) {
      setCustomMessageError('No se encontró ID del prospecto para generar mensaje.');
      return;
    }

    setLoadingCustomMessage(true);
    setCustomMessageError(null);
    setAutoGeneratedMessage(null);

    try {
      // Usar Edge Function de Supabase
      const edgeFunctionUrl = `${import.meta.env.VITE_EDGE_FUNCTIONS_URL}/functions/v1/transfer-request-proxy`;
      const response = await fetch(edgeFunctionUrl, {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${import.meta.env.VITE_ANALYSIS_SUPABASE_ANON_KEY}`
        },
        body: JSON.stringify({ prospect_id: prospectId })
      });

      if (!response.ok) {
        const errorText = await response.text().catch(() => `Error ${response.status}: ${response.statusText}`);
        setCustomMessageError(`Error al generar mensaje: ${response.status} - ${errorText.substring(0, 100)}`);
        setLoadingCustomMessage(false);
        return;
      }

      const responseData = await response.json();
      const personalizedMessage = responseData.message || responseData.transfer_message || responseData.text;

      if (!personalizedMessage || typeof personalizedMessage !== 'string') {
        setCustomMessageError('El webhook no devolvió un mensaje válido.');
        setLoadingCustomMessage(false);
        return;
      }
      
      setAutoGeneratedMessage(personalizedMessage);
      setCustomTransferMessage(personalizedMessage);
      setLoadingCustomMessage(false);
      
    } catch (error) {
      setCustomMessageError(`Error al solicitar mensaje: ${error instanceof Error ? error.message : 'Error desconocido'}`);
      setLoadingCustomMessage(false);
    }
  };

  // Función para ejecutar la transferencia
  const handleTransfer = useCallback(async () => {
    if (!call?.call_id) {
      alert('No se encontró ID de llamada');
      return;
    }

    // Determinar mensaje final
    let finalReason = '';
    if (selectedPresetReason) {
      const preset = TRANSFER_REASONS.find(r => r.short === selectedPresetReason);
      finalReason = preset ? preset.full : selectedPresetReason;
    } else if (customTransferMessage) {
      finalReason = customTransferMessage;
    }
    
    if (!finalReason || !finalReason.trim()) {
      alert('Por favor, selecciona una razón o espera el mensaje personalizado');
      return;
    }

    setTransferLoading(true);

    try {
      // Extraer contexto adicional
      let contextData = {};
      try {
        if (call.datos_llamada) {
          const datosLlamada = typeof call.datos_llamada === 'string' 
            ? JSON.parse(call.datos_llamada) 
            : call.datos_llamada;
          contextData = { ...contextData, ...datosLlamada };
        }
        
        if (call.datos_proceso) {
          const datosProc = typeof call.datos_proceso === 'string' 
            ? JSON.parse(call.datos_proceso) 
            : call.datos_proceso;
          contextData = { ...contextData, datos_proceso: datosProc };
        }
      } catch (e) {
        // No se pudo extraer contexto adicional
      }

      // Verificar control_url
      let controlUrl = call.control_url;
      
      if (!controlUrl) {
        try {
          const { data: callData, error } = await analysisSupabase
            .from('llamadas_ventas')
            .select('control_url')
            .eq('call_id', call.call_id)
            .single();
          
          if (error || !callData?.control_url) {
            alert('Error: No se encontró la URL de control. La llamada puede haber finalizado.');
            setTransferLoading(false);
            return;
          }
          
          controlUrl = callData.control_url;
        } catch (err) {
          alert('Error: No se pudo obtener la URL de control.');
          setTransferLoading(false);
          return;
        }
      }

      const transferData = {
        action: "transfer",
        call_id: call.call_id,
        control_url: controlUrl,
        message: finalReason,
        destination: {
          number: "+523222264000",
          extension: "60973"
        },
        call_context: {
          fecha_llamada: call.fecha_llamada,
          duracion_segundos: call.duracion_segundos,
          prospecto_id: call.prospecto_id,
          nombre_completo: call.nombre_completo,
          nombre_whatsapp: call.nombre_whatsapp,
          whatsapp: call.whatsapp,
          checkpoint_venta_actual: call.checkpoint_venta_actual,
          destino_preferido: call.destino_preferido,
          principales_objeciones: call.principales_objeciones,
          ...contextData
        }
      };

      // Usar Edge Function de Supabase
      const edgeFunctionUrl = `${import.meta.env.VITE_EDGE_FUNCTIONS_URL}/functions/v1/tools-proxy`;
      const response = await fetch(edgeFunctionUrl, {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${import.meta.env.VITE_ANALYSIS_SUPABASE_ANON_KEY}`
        },
        body: JSON.stringify(transferData)
      });

      if (response.ok) {
        onTransferSuccess?.();
        handleClose();
      } else {
        const errorText = await response.text();
        alert(`Error al transferir: ${errorText.substring(0, 100)}`);
      }
    } catch (error) {
      alert(`Error: ${error instanceof Error ? error.message : 'Error desconocido'}`);
    } finally {
      setTransferLoading(false);
    }
  }, [call, selectedPresetReason, customTransferMessage, onTransferSuccess]);

  // Función para cerrar y resetear
  const handleClose = useCallback(() => {
    setSelectedPresetReason('');
    setCustomTransferMessage('');
    setAutoGeneratedMessage(null);
    setCustomMessageError(null);
    setTransferLoading(false);
    setLoadingCustomMessage(false);
    onClose();
  }, [onClose]);

  if (!isOpen || !call) return null;

  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.2 }}
        className="fixed inset-0 bg-black/50 backdrop-blur-md flex items-center justify-center p-4"
        style={{ zIndex }}
        onClick={(e) => {
          if (e.target === e.currentTarget) {
            handleClose();
          }
        }}
      >
        <motion.div
          initial={{ opacity: 0, scale: 0.96, y: 10 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.96, y: 10 }}
          transition={{ duration: 0.25, ease: [0.16, 1, 0.3, 1] }}
          onClick={(e) => e.stopPropagation()}
          className="bg-white dark:bg-gray-900 rounded-2xl shadow-2xl max-w-lg w-full border border-gray-100 dark:border-gray-800"
        >
          {/* Header */}
          <div className="px-8 pt-8 pb-6 bg-gradient-to-br from-gray-50 via-white to-gray-50 dark:from-gray-900 dark:via-gray-900 dark:to-gray-800 border-b border-gray-100 dark:border-gray-800">
            <div className="flex items-center justify-between">
              <div>
                <motion.h3
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.1 }}
                  className="text-2xl font-bold text-gray-900 dark:text-white mb-1 flex items-center"
                >
                  <ArrowRightLeft className="w-6 h-6 mr-2 text-blue-500" />
                  Solicitar Transferencia
                </motion.h3>
                <motion.p
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ delay: 0.15 }}
                  className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed"
                >
                  Selecciona una razón o usa el mensaje personalizado generado
                </motion.p>
              </div>
              <motion.button
                initial={{ opacity: 0, rotate: -90 }}
                animate={{ opacity: 1, rotate: 0 }}
                transition={{ delay: 0.2 }}
                onClick={handleClose}
                className="w-10 h-10 rounded-xl flex items-center justify-center hover:bg-gray-100 dark:hover:bg-gray-800 transition-all duration-200 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 group flex-shrink-0"
                title="Cerrar"
              >
                <X className="w-5 h-5 transition-transform group-hover:rotate-90" />
              </motion.button>
            </div>
          </div>

          {/* Content */}
          <div className="px-8 py-6 overflow-y-auto max-h-[60vh] scrollbar-thin scrollbar-thumb-gray-300 dark:scrollbar-thumb-gray-700 scrollbar-track-transparent">
            {/* Razones Predefinidas */}
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="mb-6"
            >
              <div className="flex items-center space-x-2 mb-4">
                <div className="w-1 h-5 bg-gradient-to-b from-blue-500 to-purple-500 rounded-full"></div>
                <h4 className="text-sm font-semibold text-gray-700 dark:text-gray-300 uppercase tracking-wider">
                  Razones Rápidas
                </h4>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {TRANSFER_REASONS.map((reason, index) => (
                  <motion.button
                    key={reason.short}
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ delay: 0.25 + index * 0.05 }}
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    onClick={() => {
                      setSelectedPresetReason(reason.short);
                      setCustomTransferMessage('');
                    }}
                    className={`px-5 py-4 text-sm font-medium rounded-xl transition-all duration-200 text-left ${
                      selectedPresetReason === reason.short
                        ? 'bg-gradient-to-r from-blue-600 to-purple-600 text-white shadow-lg shadow-blue-500/25 border-2 border-blue-500'
                        : 'bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-800/50 dark:to-gray-800/30 text-gray-700 dark:text-gray-300 border-2 border-gray-200 dark:border-gray-700 hover:border-blue-300 dark:hover:border-blue-600'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-semibold">{reason.short}</span>
                      {selectedPresetReason === reason.short && (
                        <CheckCircle className="w-5 h-5" />
                      )}
                    </div>
                  </motion.button>
                ))}
              </div>
            </motion.div>

            {/* Mensaje Personalizado */}
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5 }}
              className="border-t border-gray-200 dark:border-gray-700 pt-6"
            >
              <div className="flex items-center space-x-2 mb-4">
                <div className="w-1 h-5 bg-gradient-to-b from-purple-500 to-pink-500 rounded-full"></div>
                <h4 className="text-sm font-semibold text-gray-700 dark:text-gray-300 uppercase tracking-wider flex items-center">
                  <Wand2 className="w-4 h-4 mr-2 text-purple-500" />
                  Mensaje Personalizado
                </h4>
              </div>
              
              {loadingCustomMessage && !autoGeneratedMessage && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="flex items-center justify-center py-8"
                >
                  <Loader2 className="w-5 h-5 animate-spin text-purple-500 mr-2" />
                  <span className="text-sm text-gray-600 dark:text-gray-400">Generando mensaje personalizado...</span>
                </motion.div>
              )}
              
              {customMessageError && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-xl p-3 mb-3"
                >
                  <p className="text-xs text-red-700 dark:text-red-300">{customMessageError}</p>
                </motion.div>
              )}
              
              {autoGeneratedMessage && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="mb-3"
                >
                  <motion.button
                    whileHover={{ scale: 1.01 }}
                    whileTap={{ scale: 0.99 }}
                    onClick={() => {
                      setCustomTransferMessage(autoGeneratedMessage);
                      setSelectedPresetReason('');
                    }}
                    className={`w-full px-5 py-4 rounded-xl border-2 shadow-lg text-left transition-all duration-200 ${
                      customTransferMessage === autoGeneratedMessage
                        ? 'bg-gradient-to-r from-purple-600 to-pink-600 text-white border-purple-500 shadow-purple-500/25'
                        : 'bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-800/50 dark:to-gray-800/30 text-gray-700 dark:text-gray-300 border-gray-200 dark:border-gray-700 hover:border-purple-300 dark:hover:border-purple-600'
                    }`}
                  >
                    <div className="flex items-center justify-between mb-2">
                      <div className="flex items-center space-x-2">
                        <Wand2 className={`w-4 h-4 ${customTransferMessage === autoGeneratedMessage ? 'text-white' : 'text-purple-500'}`} />
                        <span className="font-semibold">Mensaje Generado</span>
                      </div>
                      {customTransferMessage === autoGeneratedMessage && (
                        <CheckCircle className="w-5 h-5" />
                      )}
                    </div>
                    <p className={`text-sm mt-2 leading-relaxed ${
                      customTransferMessage === autoGeneratedMessage ? 'opacity-90' : 'opacity-75'
                    }`}>
                      {autoGeneratedMessage}
                    </p>
                  </motion.button>
                </motion.div>
              )}
            </motion.div>
          </div>

          {/* Footer */}
          <div className="px-8 py-5 border-t border-gray-100 dark:border-gray-800 bg-gray-50/50 dark:bg-gray-900/50 flex justify-end space-x-3">
            <motion.button
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.25 }}
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              onClick={handleClose}
              className="px-5 py-2.5 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl hover:bg-gray-50 dark:hover:bg-gray-700 transition-all duration-200"
            >
              Cancelar
            </motion.button>
            <motion.button
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.3 }}
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              onClick={handleTransfer}
              disabled={transferLoading || (!selectedPresetReason && !customTransferMessage)}
              className="px-5 py-2.5 text-sm font-medium text-white bg-gradient-to-r from-blue-600 to-purple-600 rounded-xl hover:from-blue-700 hover:to-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200 shadow-lg shadow-blue-500/25 flex items-center"
            >
              <RotateCcw className="w-4 h-4 mr-2" />
              {transferLoading ? 'Transfiriendo...' : 'Transferir Llamada'}
            </motion.button>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
};

export default TransferModal;
