#!/bin/bash
echo "=== Diagnóstico de Supabase ==="
echo "Fecha: $(date)"
echo ""
echo "1. Estado del sistema:"
uptime
echo ""
echo "2. Servicios Docker:"
docker ps -a 2>/dev/null || echo "Docker no está instalado o no está corriendo"
echo ""
echo "3. Docker Compose:"
cd /home/ubuntu/supabase/docker 2>/dev/null && docker-compose ps || echo "No se encontró docker-compose o supabase/docker"
echo ""
echo "4. Puertos en escucha:"
netstat -tlnp 2>/dev/null | grep -E ":(3000|8000|5432|8080)" || ss -tlnp 2>/dev/null | grep -E ":(3000|8000|5432|8080)" || echo "No se encontraron puertos relevantes"
echo ""
echo "5. Últimos logs de user-data:"
tail -100 /var/log/user-data.log 2>/dev/null || echo "No hay logs de user-data"
echo ""
echo "6. Últimos logs de cloud-init:"
tail -100 /var/log/cloud-init-output.log 2>/dev/null || echo "No hay logs de cloud-init"
echo ""
echo "7. Verificando si Supabase está corriendo:"
curl -I http://localhost:3000 2>&1 | head -5 || echo "No se puede conectar a localhost:3000"
